apiVersion: v1
kind: Service
metadata:
  name: capstone-service-$BRANCH_NAME
  labels:
    app: capstone-$BRANCH_NAME
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # from inside the cluster use the DNS name 'capstone-service' on port 8080
    targetPort: 80 # This is the port on the pod that the request gets sent to
    nodePort: $NODE_PORT # from outside the cluster hit any node on this port to access
  selector:
    app: capstone-$BRANCH_NAME

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-$BRANCH_NAME
  labels:
    app: capstone-$BRANCH_NAME
spec:
  replicas: 8
  selector:
    matchLabels:
      app: capstone-$BRANCH_NAME
  minReadySeconds: 10
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: capstone-$BRANCH_NAME
    spec:
      containers:
      - name: capstone-$BRANCH_NAME
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80