apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # from inside the cluster use the DNS name 'capstone-service' on port 8080
    targetPort: 80 # This is the port on the pod that the request gets sent to
    nodePort: 30001 # from outside the cluster hit any node on this port to acess
  selector:
    app: capstone

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-$BRANCH_NAME
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80