Description:
  Robert Foster
  Udacity / Capstone
  K8s

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String

Resources:

  EC2K8s1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-01ed306a12b7d1c96"
      InstanceType: "t2.small"
      Tags:
        - Key: Name
          Value : !Sub ${EnvironmentName}-k8s-1
      KeyName: "capstone-keypair"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
          - Ref: K8sSecGroup
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-publicsubnet1-id

  EC2K8s2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-01ed306a12b7d1c96"
      InstanceType: "t2.small"
      Tags:
        - Key: Name
          Value : !Sub ${EnvironmentName}-k8s-2
      KeyName: "capstone-keypair"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
          - Ref: K8sSecGroup
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-publicsubnet1-id

  EC2K8s3: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-01ed306a12b7d1c96"
      InstanceType: "t2.small"
      Tags:
        - Key: Name
          Value : !Sub ${EnvironmentName}-k8s-3
      KeyName: "capstone-keypair"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
          - Ref: K8sSecGroup
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-publicsubnet1-id

  K8sSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow access to K8s
      VpcId:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 146.199.83.97/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 157.140.121.86/32
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 146.199.83.97/32
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 157.140.121.86/32
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.4.0.0/24
        - IpProtocol: tcp
          FromPort: 30001
          ToPort: 30020
          CidrIp: 146.199.83.97/32
        - IpProtocol: tcp
          FromPort: 30001
          ToPort: 30020
          CidrIp: 157.140.121.86/32
      Tags: 
        - Key: Name 
          Value: !Sub ${EnvironmentName}-k8s-sg
      GroupName: !Sub ${EnvironmentName}-k8s-sg
  
 
